<a href="https://colab.research.google.com/github/logansdmi/CurveFitting/blob/main/Sudoku.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Sudoku solver ##

This uses a recursive backtracking algorithm to try new values in a sudoku problem.

In [1]:
import numpy as np
import time


def rules(y,x,attempt,problem):
  #global problem
  '''inputs: y,x - positions in the matrix, attempt - the number attemping to be fitted into problem,
  problem - matrix of numbers representign a sudoku problem
  outputs - true or false depending if the attempt fits the position'''
  # testing if attempt can fit in a row
  for i in range(9):
    if problem[i][x] == attempt:
      return False
  # testing of attempt can fit in a column
  for i in range(9):
    if problem[y][i] == attempt:
      return False
  # testing if the attempt can fit into the 3x3 boxes
  xBox = 3 * (x//3)
  yBox = 3 * (y//3)
  for i in range(3):
    for j in range(3):
      if problem[yBox + i][xBox + j] == attempt:
        return False
  return True 

def solver(problem):
  '''input: problem - matrix representing the sudoku problem
  output - the solved problem in matrix form'''
  # loops through all x and y values
  for y in range(9):
    for x in range(9):
      # checks if the position is empty
      if problem[y][x] == 0:
        for attempt in range(1,10): # loops through each attempt posible
          if rules(y,x,attempt,problem): # checks if attempt is possible
            problem[y][x] = attempt # puts the attempt into the problem
            # the problem is solved again with the new value in but if it does not lead to a solution the attempt is removed and a new one is tried
            solver(problem) 
            problem[y][x] = 0
        return 
  # prints solved problem and allows user to try another solution
  print(np.matrix(problem))
  return
  #input('Another solution?[press enter]')
    


In [2]:
problem1 = [
    [7, 8, 0, 4, 0, 0, 1, 2, 0],
    [6, 0, 0, 0, 7, 5, 0, 0, 9],
    [0, 0, 0, 6, 0, 1, 0, 7, 8],
    [0, 0, 7, 0, 4, 0, 2, 6, 0],
    [0, 0, 1, 0, 5, 0, 9, 3, 0],
    [9, 0, 4, 0, 6, 0, 0, 0, 5],
    [0, 7, 0, 3, 0, 0, 0, 1, 2],
    [1, 2, 0, 0, 0, 7, 4, 0, 0],
    [0, 4, 9, 2, 0, 6, 0, 0, 7]
]
problem2 = [
    [8, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 3, 6, 0, 0, 0, 0, 0],
    [0, 7, 0, 0, 9, 0, 2, 0, 0],
    [0, 5, 0, 0, 0, 7, 0, 0, 0],
    [0, 0, 0, 0, 4, 5, 7, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 3, 0],
    [0, 0, 1, 0, 0, 0, 0, 6, 8],
    [0, 0, 8, 5, 0, 0, 0, 1, 0],
    [0, 9, 0, 0, 0, 0, 4, 0, 0]
]
#print(np.matrix(problem1))


[[7 8 0 4 0 0 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


In [3]:

solver(problem2)


[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]
time elapsed: 29.278582334518433
